# Generated by Django 3.0.6 on 2020-05-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=255)),
                ('game_short_description', models.CharField(max_length=255)),
                ('game_long_description', models.CharField(max_length=999)),
                ('game_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_genre_name', models.CharField(max_length=255)),
                ('game_genre_image', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GamePublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_publisher_name', models.CharField(max_length=255)),
                ('game_publisher_description', models.CharField(max_length=999)),
                ('game_publisher_logo', models.CharField(blank=True, max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_image_image', models.CharField(max_length=999)),
                ('game_image_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameGenre'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GamePublisher'),
        ),
    ]
