# Generated by Django 3.0.6 on 2020-05-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_name', models.CharField(max_length=255)),
                ('console_short_description', models.CharField(max_length=255)),
                ('console_long_description', models.CharField(max_length=999)),
                ('console_specs', models.CharField(max_length=999)),
                ('console_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_category_name', models.CharField(max_length=255)),
                ('console_category_image', models.CharField(blank=True, max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('manufacturer_description', models.CharField(max_length=999)),
                ('manufacturer_logo', models.CharField(blank=True, max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_image_image', models.CharField(max_length=999)),
                ('console_image_console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.Console')),
            ],
        ),
        migrations.AddField(
            model_name='console',
            name='console_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.ConsoleCategory'),
        ),
        migrations.AddField(
            model_name='console',
            name='console_manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.ManufacturerCategory'),
        ),
    ]
