# Generated by Django 3.0.6 on 2020-05-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='console_specs',
        ),
    ]
