# Generated by Django 3.0.6 on 2020-05-15 16:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20200515_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('house_number', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(1), django.core.validators.MinLengthValidator(5)])),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
                ('card_holder', models.CharField(max_length=255)),
                ('card_number', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)])),
                ('expiry_date', models.CharField(max_length=255)),
                ('cvc_number', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.AlterField(
            model_name='order',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.BillingProfile'),
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
    ]
