# Generated by Django 3.0.6 on 2020-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='card_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='cvc_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='house_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='zip_code',
            field=models.CharField(max_length=255),
        ),
    ]
